import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Remember"
include ':app'
include ':notes'
include ':common-ui'
include ':tasks'
include ':core'
include ':tasks:data'
include ':core:db'
include ':core:ui'
include ':core:android-util'
include ':tasks:domain'
include ':core:util'
include ':notes:domain'
include ':notes:data'
include ':core:di'
include ':shared:util'
