plugins {
    id 'com.rms.android-library.plugin'
    id 'com.rms.module-compose.plugin'
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.metro)
}

android {
    namespace 'com.rms.tasks'
}

dependencies {
    implementation project(':core:ui')
    implementation project(':shared:core:db')
    implementation project(':core:di')
    implementation project(':shared:util')
    implementation project(':core:util')
    api project(':shared:feature:tasks:presentation')

    implementation libs.compose.dialog.datetime

}