plugins {
    id("com.rms.android-library.plugin")
    id("com.rms.module-compose.plugin")
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.metro)
}

android {
    namespace 'com.rms.notes'
}

dependencies {
    implementation project(':core:ui')
    implementation project(':shared:core:db')
    api project(':shared:feature:notes:presentation')
    implementation project(':core:di')
}